// <auto-generated />
namespace CollidR.Sample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class requirethatname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requirethatname));
        
        string IMigrationMetadata.Id
        {
            get { return "201309162254564_requirethatname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
